### ISSUE TITLE
Bling crash report

### ISSUE THREAD

**Issue by clellandm** [lurume84/bling-desktop#12]
I think I added my crash report to some other app you've written.  Bling seems like the missing piece of Blink - thanks for building it!  I had a couple of fast crashes that I've attached.  Also, how do I access live view - I don't see that, but it is mentioned in the readme.
[CrashRpt-Log-20190715-122635-{fba7ab63-647f-4eae-a30a-798a10dc0c79}.txt](https://github.com/lurume84/bling-desktop/files/3393306/CrashRpt-Log-20190715-122635-.fba7ab63-647f-4eae-a30a-798a10dc0c79.txt)
[CrashRpt-Log-20190715-120621-{7d993511-e19b-4989-a09b-5f25ab136260}.txt](https://github.com/lurume84/bling-desktop/files/3393307/CrashRpt-Log-20190715-120621-.7d993511-e19b-4989-a09b-5f25ab136260.txt)
[CrashRpt-Log-20190715-121820-{773c4b0a-8786-41ec-969e-1e9ce938cf13}.txt](https://github.com/lurume84/bling-desktop/files/3393308/CrashRpt-Log-20190715-121820-.773c4b0a-8786-41ec-969e-1e9ce938cf13.txt)

**Comment by lurume84** [comment]
Hi, no worries. I need the zip file located at

C:\Users\clell\Documents\Bling.exe\CrashReports\\7d993511-e19b-4989-a09b-5f25ab136260.zip

Attach it here as you did with txt files and I will see which the problem is.

I am about to release a new version that includes live view. Hopefully this week will be published!

**Comment by clellandm** [comment]
HA!, "We don't support that file type", I'll try sending to your reply email!   Also I am not seeing notifications, is that in a future version as well?  :)

**Comment by lurume84** [comment]
Yes, you can reach me at lurume84 gmail. If you are using Windows 7, notifications are not supported in this OS. If you are using Windows 10 you should see them unless you have notifications in Windows 10 disabled. Notifications may be related with your crash.

**Comment by clellandm** [comment]
Duh, the .zip I tried attaching was really a .zip.md5.  Maybe this time...
[fba7ab63-647f-4eae-a30a-798a10dc0c79.zip](https://github.com/lurume84/bling-desktop/files/3393709/fba7ab63-647f-4eae-a30a-798a10dc0c79.zip)
[7d993511-e19b-4989-a09b-5f25ab136260.zip](https://github.com/lurume84/bling-desktop/files/3393710/7d993511-e19b-4989-a09b-5f25ab136260.zip)
[773c4b0a-8786-41ec-969e-1e9ce938cf13.zip](https://github.com/lurume84/bling-desktop/files/3393711/773c4b0a-8786-41ec-969e-1e9ce938cf13.zip)

**Comment by lurume84** [comment]
Your crashes are produced during video synchronization. I cannot reproduce it but I have released a new version that has updated all this functionality so please upgrade and let's see if it works ok. 

On a separate note, this release includes Live View support so you will be able to see your cameras live and this video will be automatically saved in your hard drive.

**Comment by hobbzey** [comment]
Windows 7 user here. Last version that added win7 support works great, but the latest version with live view will not open. Crash dump zips attached.

[fad9e9e3-926e-4e58-b85b-720ed4f28427.zip](https://github.com/lurume84/bling-desktop/files/3422220/fad9e9e3-926e-4e58-b85b-720ed4f28427.zip)
[3f45a4b2-aeb1-4186-bf25-25b4f90369e9.zip](https://github.com/lurume84/bling-desktop/files/3422221/3f45a4b2-aeb1-4186-bf25-25b4f90369e9.zip)
[dc21462f-0d2b-401e-8a75-3b81da118160.zip](https://github.com/lurume84/bling-desktop/files/3422222/dc21462f-0d2b-401e-8a75-3b81da118160.zip)
[df6f32f4-c900-44a3-87a1-29b9681ab0ad.zip](https://github.com/lurume84/bling-desktop/files/3422223/df6f32f4-c900-44a3-87a1-29b9681ab0ad.zip)

**Comment by lurume84** [comment]
Oh, sorry for that. I could reproduce the issue, seems to be related with new webserver used to serve the video streaming. Close any instance of BlingW7.exe (check in Task Manager) and execute with elevated permissions i.e. right click in executable and run as administrator. For some reason Microsoft's library cpprestsdk needs to have elevated permissions in this OS in order to work. If this does not solve the issue it may be produced because port 9191 in your machine is in use, it can be changed through Blink.ini file, check documentation in that case.

Check first running as admin and let's see if the application works.

**Comment by lurume84** [comment]
I have moved to another webserver library so crashes should be gone. Additionally, the reasons why process was not being closed have also been corrected. Download last version and check again.
