### ISSUE TITLE
Resize live view boxes

### ISSUE THREAD

**Issue by vampywiz17** [lurume84/bling-desktop#14]
@lurume84 

Hello there, 

it possible to add a option to resize the live view box?

The full screen is too big sometimes, the normal view is to small :)

I think a good size is the same with recorded videos playback size.

Anyway, the live view option is awsome!!

**Comment by lurume84** [comment]
Hi, I just released a new version with a slider that controls box size at the bottom of the page. The problem is it is not persisted at this time so needs to be set every time you navigate to it. Next time you open app it should inform about a new release.

Live view has been a quite challenging feature to integrate, glad you like it!

**Comment by vampywiz17** [comment]
Great! Working well :) It is a really fast and good work! Thanks a lot!
