### ISSUE TITLE
Bling crash if i started second time

### ISSUE THREAD

**Issue by vampywiz17** [lurume84/bling-desktop#16]
Hello there,

If i start Bling first time that i start my PC, it working well. But if i close it and start it a later time, it crashed. 

The reason that a the "DesktopApp.exe" is running in the backround, after i close the program. If i force close it with task manager, i able to start Bling again , without crash.

I send the crash report to you, i think you found it, (send it a more that one time)

**Comment by lurume84** [comment]
Yes, this is because there is a webserver inside to support live view. Since there is another instance running, port is not available and makes application crash. There are two issues here since blingapp should never be left open in the background. It could be related with closing app during a live view in process.

I will solve it for next release as it is a bit more complex to generate desktop releases compared with the viewer ones it may delay a little. Your workaround is completely valid and in case you cannot start after reboot just change port through ini file. Documentation explains how to do it.

Did you send the dump to my email? Is the one begining with a6acec1c? Just to not answer there again. Regards

**Comment by vampywiz17** [comment]
I upload now is here https://ufile.io/mgwmrhcq

**Comment by lurume84** [comment]
I have moved to another webserver library so crashes should be gone. Additionally, the reasons why process was not being closed have also been corrected. Download last version and check again.
