### ISSUE TITLE
Empty view

### ISSUE THREAD

**Issue by sutty550e** [lurume84/bling-desktop#2]
Having just installed the latest msi version, it ran fine, with no errors on start-up and I was able to log-in, but now I see no snapshots, or videos. All I get is a blank screen for each sync module. Also, About, Contact, and Legal information, seem to do nothing.

**Comment by lurume84** [comment]
This happened in viewer 0.1.3 because of new Blink app update. Close the app and check if inside my docs/Bling.exe/Download/Versions/ there is a v0.1.4.zip. If so, delete this file, go to %appdata%\Bling Desktop\Html and remove viewer folder.

Then open the app and viewer will be downloaded fresh. If error persists it's a viewer problem and may be related to something I could not foresee with my account. Check this first and if error persist I will release a new version with traces to diagnose the problem.

**Comment by sutty550e** [comment]
Hello lurum84

This worked fine, and the view is back.

Thank you.
