### ISSUE TITLE
Few issue 

### ISSUE THREAD

**Issue by gokis** [lurume84/bling-desktop#22]
Hi, app is great thanks for it! But there is few think what it make that even better if that possible to do.
1. Keeps log you off after around 20h so I need to remember to get kill the app and open again to sync videos
2. Live view at windows 10 not work keep getting black screen with loading
3. Is the any way you can make them recording in live view all the time ? I know if I left them open on Alexa show it’s recording until I tell Alexa to stop I am able to pay for it

**Comment by lurume84** [comment]
You probably have XT2 cameras. Live view does not work for these ones, it's quite complex to make it work and I only have XT to make it worse. Live View is limited by Blink's mobile App. Bling application records while retransmits Live View and can be left open indefinitely (in theory).

It's strange the log off you suffer since application eventually checks for more videos so a login is done with that token. Could be related to having different tokens login from different applications. I haven't seen this but will leave open my app following days.
