### ISSUE TITLE
version 0.1.19 - Only downloads 1 video on startup.

### ISSUE THREAD

**Issue by BillRedfern** [lurume84/bling-desktop#29]
Windows 10.
The latest version only download a single video on startup. Previous version downloaded all the videos from the LastUpdate value. I have not made any changes to the ini file from my previous setup.

**Comment by lurume84** [comment]
Yes, I am releasing a new version today correcting this

**Comment by lurume84** [comment]
Done!

This new version also allows to disable automatic desktop and viewer upgrades through Bling.ini with

[UpgradeDesktop]
Enabled=false
[UpgradeViewer]
Enabled=false

Just in case you need a stable release because I will be improving the application these days and may be a bit frustrating having issues in case you really need to get the videos.
