### ISSUE TITLE
Manual Thumbnail

### ISSUE THREAD

**Issue by sutty550e** [lurume84/bling-desktop#6]
Hello Luis

If I've forgotten and it's been mentioned already, please accept my apologies, but I would really like the option to simply request a new thumbnail, manually, as and when required. A button or link under each thumb view would be perfect. The auto feature is nice, but I suspect overkill for most. It does work well though.

Also, how do I send you a PM or an email. I would like to ask you something else, that doesn't relate directly to this project.

Thanks

Andrew

**Comment by lurume84** [comment]
It was actually done last week during automatic implementation but in the viewer project. I imagine the problem is you do not receive the viewer update notification because notifications were not working in your computer. Check if your current viewer version is 0.1.5 (go to %userprofile%/Documents/Bling.exe/Download/Versions). 

You have two solutions: 

Either download this viewer version https://github.com/lurume84/bling-viewer/releases/tag/v0.1.5 and extract in %appdata%\Bling Desktop\Html\viewer. 

Or delete %appdata%\Bling Desktop\Html\viewer folder contents and all zips inside %userprofile%/Documents/Bling.exe/Download/Versions, next time you open the app it will upgrade to the last one.

I encourage you to investigate why notifications do not work on your computer so you can get last updates ASAP and without intervention.

You can mail me to at gmail using my github nick name.

**Comment by sutty550e** [comment]
Thanks Luis, I have updated the folder with the latest viewer, and now see the camera icon. Having pressed it, my thumbnail view updated, but no new download of the thumbnail was provided in my bling.exe download sub-folder. Auto updates did populate the folder, manual does not seem to, unless I missed something.

With regard to notifications, I'll explain in an email, because if I do have an issue, then it's outside of the scope of your development thread.

Thanks again.

**Comment by lurume84** [comment]
As this is implemented in the viewer, manual update just updates the snapshot. For also saving, the fastest thing we can do is to allow save that thumbnail with a save dialog. This can be easily done, automatic save needs more implementation but can also be done. In the mean time first thing would be fine right?

**Comment by sutty550e** [comment]
Yes, that would be absolutely fine. Nice one.

**Comment by PeteCress** [comment]
Sutty:  
Got your code, works a-ok on my Win 10 laptop, next stop Windows 7 Desktop.... Installed SDK, currently bringing 7 up to current rev in hopes of getting PowerShell 3.0, which seems tb needed for the ConvertTo-json and Invoke-RestMethod commands.

Also got the part about email being more convenient, but I cannot find your email addr.

How about flipping me an email at Confirm@FatBelly.com with your email addy in it?
