### ISSUE TITLE
Latest release will not launch app after install.

### ISSUE THREAD

**Issue by sutty550e** [lurume84/bling-desktop#8]
Hello Luis

I just replaced my install with the new .exe version, and the application will not start properly. I just get the timer circle swirling around and around, seemingly indefinitely.

Thanks

Andrew

**Comment by sutty550e** [comment]
Also, how do I uninstall it, and go back to a previous install? I don't see it in my list of apps to uninstall.

Thanks again

Andrew

**Comment by lurume84** [comment]
This happens because current viewer was extracted in installation folder. Since you already have the latest viewer downloaded in %bling.exe%/Download/Versions it thinks it is updated but it is not. Thi new version extracts viewer in %bling.exe% so this never happens again.

To solve this, just remove anything inside download/versions and execute again.

Installation is done with another tool so it is not backwards compatible with the previous one. For uninstalling you may have to go to %localappdata%/Bling Desktop and execute uninstall. In future releases I will add shortcuts for windows.

Software upgrades is a bit of a mess right now but for next release I will try to make this as transparent as possible.

**Comment by sutty550e** [comment]
Hello Luis

That has resolved the issue, and allowed me to launch.

Thank you.

Andrew
